title: Joe Gonwa
baseURL: "https://joegonwa.com"
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
ignoreLogs: ['warning-partial-superfluous-prefix']

params:
  description: "Writing, projects, and reflections by Joe Gonwa"
  author: Joe Gonwa
  DateFormat: "2006-01-02"
  defaultTheme: auto  # light, dark, auto
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  mainSections:
    - projects
    - writing
    - margins
  hideSearch: true

  assets:
    favicon: "favicon.png"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"
    theme_color: "#2e2e33"
    msapplication_TileColor: "#2e2e33"

  homeInfoParams:
    Title: "Hi, I'm Joe."
    Content: >
      This site is where I focus, build, and think out loud.

  socialIcons:
    - name: github
      url: "https://github.com/yogonwa"
    - name: linkedin
      url: "https://www.linkedin.com/in/joe-gonwa/"

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Writing
      url: /writing/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Now
      url: /now/
      weight: 4


outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
