title: Joe Gonwa
baseURL: "https://joegonwa.com"
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
ignoreLogs: ['warning-partial-superfluous-prefix']

params:
  description: "Writing, projects, and reflections by Joe Gonwa"
  author: Joe Gonwa
  favicon: "favicon.svg"
  faviconIco: "favicon.ico"
  appleTouchIcon: "apple-touch-icon.png"
  webManifest: "site.webmanifest"
  DateFormat: "2006-01-02"
  defaultTheme: auto  # light, dark, auto
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  mainSections:
    - projects
    - writing
    - margins
  hideSearch: true

  homeInfoParams:
    Title: "Hi, I'm Joe."
    Content: >
      This site is where I focus, build, and think out loud.

  socialIcons:
    - name: github
      url: "https://github.com/yogonwa"
    - name: linkedin
      url: "https://www.linkedin.com/in/joe-gonwa/"

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Writing
      url: /writing/
      weight: 2
    - name: Margins
      url: /margins/
      weight: 3
    - name: Projects
      url: /projects/
      weight: 4
    - name: Reading
      url: /reading/
      weight: 5
    - name: Now
      url: /now/
      weight: 6


outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
