title: Joe Gonwa
baseURL: "https://joegonwa.com"
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
ignoreLogs: ['warning-partial-superfluous-prefix']

params:
  description: "Writing, projects, and reflections by Joe Gonwa"
  author: Joe Gonwa
  favicon: "favicon.png"
  DateFormat: "2006-01-02"
  defaultTheme: auto  # light, dark, auto
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: "Hi, I'm Joe."
    Content: >
      I'm a product manager, writer, and tinkerer. This is my personal corner of the internet—where I think in public, track projects, and write about what's capturing my attention.

  socialIcons:
    - name: github
      url: "https://github.com/yogonwa"
    - name: linkedin
      url: "https://linkedin.com/in/your-linkedin-username"

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Writing
      url: /writing/
      weight: 2
    - name: Margins
      url: /margins/
      weight: 3
    - name: Projects
      url: /projects/
      weight: 4
    - name: Reading
      url: /reading/
      weight: 5
    - name: Now
      url: /now/
      weight: 6
    - name: Contact
      url: /contact/
      weight: 7

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
